### ISSUE TITLE
AwsDiscoveryStrategy.discoverNodes throws exception causes node to shutdown immediately

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-aws#64] opened 2018-04-06 20:53 UTC
When member try to make the initial connection, `DiscoveryJoiner.getPossibleAddressesForInitialJoin` called, which calls `AwsDiscoveryStrategy.discoverNodes`. If any exception happens, this goes all the way back to `TCPJoiner` & causes node to shut down immediately instead of waiting to join. See below exception. Is this an expected behaviour?

```

2018-04-06 16:08:18,927Z INFO  [main] com.hazelcast.instance.Node - [10.205.89.32]:11415 [dev] [3.9.3] Activating Discovery SPI Joiner

2018-04-06 16:08:19,027Z INFO  [main] com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl - [10.205.89.32]:11415 [dev] [3.9.3] Starting 16 partition threads and 9 generic threads (1 dedicated for priority tasks)

2018-04-06 16:08:19,030Z INFO  [main] com.hazelcast.internal.diagnostics.Diagnostics - [10.205.89.32]:11415 [dev] [3.9.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.

2018-04-06 16:08:19,034Z INFO  [main] com.hazelcast.core.LifecycleService - [10.205.89.32]:11415 [dev] [3.9.3] [10.205.89.32]:11415 is STARTING

2018-04-06 16:08:19,056Z INFO  [main] com.hazelcast.system - [10.205.89.32]:11415 [dev] [3.9.3] Cluster version set to 3.9

2018-04-06 16:08:19,064Z INFO  [main] com.hazelcast.spi.hotrestart - [10.205.89.32]:11415 [dev] [3.9.3] hz._hzInstance_1_dev.s00 homeDir: /home/ec2-user/HR_DATA/s00

2018-04-06 16:08:19,086Z INFO  [main] com.hazelcast.spi.hotrestart - [10.205.89.32]:11415 [dev] [3.9.3] hz._hzInstance_1_dev.s01 homeDir: /home/ec2-user/HR_DATA/s01

2018-04-06 16:08:29,213Z ERROR [main] com.hazelcast.internal.cluster.impl.DiscoveryJoiner - [10.205.89.32]:11415 [dev] [3.9.3] java.net.SocketTimeoutException: connect timed out

com.hazelcast.core.HazelcastException: java.net.SocketTimeoutException: connect timed out

      at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)

      at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)

      at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)

      at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)

      at com.hazelcast.aws.AwsDiscoveryStrategy.discoverNodes(AwsDiscoveryStrategy.java:167)

      at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:74)

      at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:70)

      at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddressesForInitialJoin(DiscoveryJoiner.java:59)

      at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:131)

      at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:90)

      at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:134)

      at com.hazelcast.instance.Node.join(Node.java:690)

      at com.hazelcast.instance.Node.start(Node.java:390)

      at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)

      at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)

      at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)

      at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)

      at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)

      at com.vertex.c1.hotrestart.HRMain.runServer(HRMain.java:429)

      at com.vertex.c1.hotrestart.HRMain.run(HRMain.java:167)

      at com.vertex.c1.hotrestart.HRMain.main(HRMain.java:146)

Caused by: java.net.SocketTimeoutException: connect timed out

      at java.net.PlainSocketImpl.socketConnect(Native Method)

      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

      at java.net.Socket.connect(Socket.java:589)

      at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)

      at sun.net.NetworkClient.doConnect(NetworkClient.java:175)

      at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)

      at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)

      at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)

      at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)

      at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)

      at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)

      at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)

      at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)

      at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)

      at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:243)

      at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:227)

      at com.hazelcast.aws.AWSClient.getAddresses(AWSClient.java:56)

      at com.hazelcast.aws.AwsDiscoveryStrategy.discoverNodes(AwsDiscoveryStrategy.java:146)

      ... 16 more

2018-04-06 16:08:29,216Z ERROR [main] com.hazelcast.instance.Node - [10.205.89.32]:11415 [dev] [3.9.3] Could not join cluster in 300000 ms. Shutting down now!
```

**Comment by gokhanoner** [comment] 2018-04-06 21:10
Please see https://github.com/hazelcast/hazelcast/pull/12581

This could need to be fixed on core side instead of AWS.

**Comment by gokhanoner** [comment] 2018-04-09 17:38
Related Zendesk issue: https://hazelcast.zendesk.com/agent/tickets/3809

**Comment by mesutcelik** [comment] 2018-04-09 18:08
related to https://github.com/hazelcast/hazelcast-aws/issues/28

**Comment by gokhanoner** [comment] 2018-05-09 05:10
@mesutcelik , @leszko do you think that this should be fixed in aws repo or in the core, since it affects all SPI discoveries?

**Comment by leszko** [comment] 2018-05-09 11:43
@gokhanoner, why do you think it affects other environments than AWS?

**Comment by leszko** [comment] 2018-05-09 12:34
Ok, if both are observed only in AWS, I'd assume it's related to AWS only. So, we can keep this issue here and link it form Zendesk.

**Comment by mesutcelik** [comment] 2018-05-09 15:17
I think the current behavior seems correct. the difference between this issue and client is that client retry mechanism wasn't working because of unhandled exception on the client side. I think we need to shutdown the member if it can't fetch IPs of the other cluster members. However, we need to define the cases of such failures and put proper logging otherwise Ops Guys would not know how to correct the cause behind fail fast shutdown situation.

@leszko I suggest you to investigate with @gokhanoner and try to reproduce his case...

**Comment by leszko** [comment] 2018-05-22 02:50
The issue will be fixed by #71.

@ps-jay , the issue is really only about the retries. The log you see is actually wrong, Hazelcast does not wait "300000 ms" before printing this message. I've sent a fix for that (hazelcast/hazelcast#13164).

**Comment by ps-jay** [comment] 2018-05-22 02:54
So the fix will be that Hazelcast won't shutdown if enountering AWS throttling on startup?

**Comment by leszko** [comment] 2018-05-22 12:26
yes, but also it will retry the number of times specified by the parameter and only then return an empty list. So in result, if there is no connection to AWS, you may end up with the Split Brain, but Hazelcast won't shutdown.

**Closed** 2018-05-30 12:47 UTC
Labels: Estimation: M, Priority: High, Type: Defect
