### ISSUE TITLE
Hazlecast node repeated close connection to itself.

### ISSUE THREAD

**Issue by osnatn** [hazelcast/hazelcast-aws#19] opened 2017-02-09 08:15 UTC
Hi,

Attached files:
[clusterInfo.txt](https://github.com/hazelcast/hazelcast-aws/files/763009/clusterInfo.txt)
[network-config.txt](https://github.com/hazelcast/hazelcast-aws/files/763010/network-config.txt)

I’m having some problems using Hazelcast in my project, using aws-discovery and docker.
1.	I see exceptions in logs.
2.	I see in the logs of one of the two nodes (not the master/old node) repeated (each 2min) close connection with – “Reason: Connection closed by the other side”
The close connection message refers to the node try to connect to itself which I don’t know why required at all. 

Here are the details (long, sorry…) 

We have several instances of our servers deployed in amazon with load balancer so number of instances can vary according to traffic.
The servers are deployed with Docker and amazon cloud-formation.
Each of those servers is now also a hazelcast node with shared IMap data, currently I’m working with two server instances (two hazelcast nodes).

I’m using aws auto-discovery and supplying, on hazelcast instance creation, configuration as below with server’s tag and security-group, for proper discovery match.
networkConfig.getJoin().getMulticastConfig().setEnabled(false);
networkConfig.getJoin().getTcpIpConfig().setEnabled(false);

AwsConfig awsConfig = networkConfig.getJoin().getAwsConfig();
awsConfig.setEnabled(true);
awsConfig.setAccessKey(myAWSAccessKey);
awsConfig.setSecretKey(myAWSSecretKey);
awsConfig.setRegion(myRegion);
awsConfig.setSecurityGroupName(mySecurityGroupName);
awsConfig.setTagKey(myTagKeyName);
awsConfig.setTagValue(myTagKeyValue);
awsConfig.setIamRole(null);
awsConfig.setConnectionTimeoutSeconds(myTimeout);
networkConfig.getJoin().getTcpIpConfig().setConnectionTimeoutSeconds(myTimeout);

In addition, I’m using only 4 ports – 5701, 5702, 5703, 5704 which are opened, hazelcast configuration is updated with: 
networkConfig.setPort(5701);
networkConfig.setPortCount(4);
networkConfig.setPortAutoIncrement(true);

Also I set to true the ReuseAddress although I don’t think required. 
networkConfig.setReuseAddress(true);

The auto-discovery seemed to work ok but since I’m working with Docker, hazelcast used the docker-ip instead of the server aws ip so the tcp/ip connection fails.
I found online, a suggested solution which I’m using and it seems to cause the tcp/ip connection to work.
privateIpAddress = get the server aws private-ip.
networkConfig.setPublicAddress(privateIpAddress);
config.setProperty("hazelcast.local.localAddress", privateIpAddress);

All of the above resulted with proper hazelcast memner initialization as seen below in logs:
Members [2] {
        Member [100.125.228.50]:5701 - ffbc4126-a780-460e-ac8d-7a021367f371 this
        Member [100.125.238.93]:5701 - 4306bb9f-5761-4aaf-986e-f57ba716cfb7
}

And now to the problem…

The logs of the server which is the master hazelcast node (100.125.238.93) seems ok, 
but the logs of the 2nd server/node (100.125.228.50) has some exceptions from time to time and in addition I see repeated connection close (every 2min) as:

2017-02-07 08:54:24.651  INFO 1 --- [hz._hzInstance_1_web-wfa2.cached.thread-1] c.h.nio.tcp.TcpIpConnectionManager       : 
[100.125.228.50]:5701 [web-wfa2] [3.7] Established socket connection between /172.17.0.4:41880 and /100.125.228.50:5702

2017-02-07 08:54:24.651  INFO 1 --- [hz._hzInstance_1_web-wfa2.IO.thread-in-2] com.hazelcast.nio.tcp.TcpIpConnection    : 
[100.125.228.50]:5701 [web-wfa2] [3.7] Connection[id=930, /172.17.0.4:41880->/100.125.228.50:5702, endpoint=[100.125.228.50]:5702, alive=false, type=NONE] closed. 
Reason: Connection closed by the other side

Please note that the connections close refers to connection of the node to itself according to above log  - 100.125.228.50:5701 tries to connect to 100.125.228.50:5702 , with close Reason: Connection closed by the other side (?!?)
The ip - 172.17.0.4:41880  appearing in above log  is the docker-ip, and from checking the hazelcast code I see that it refers to the LocalSocketAddress:
  this.logger.info("Established socket connection between " + channel.socket().getLocalSocketAddress() + " and " + channel.socket().getRemoteSocketAddress());

I don’t think the docker-ip in the logs represents a problem since it appears also with an OK connection to the 1st server (100.125.238.93):
2017-02-06 17:09:20.057  INFO 1 --- [hz._hzInstance_1_web-wfa2.cached.thread-11] c.h.nio.tcp.TcpIpConnectionManager       : 
[100.125.228.50]:5701 [web-wfa2] [3.7] Established socket connection between /172.17.0.4:5701 and /100.125.238.93:54378

Yet, I do not understand why the connection is closed repeatedly and not sure why it tries to connect to itself.

Also there are disturbing exceptions in the logs:

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at com.hazelcast.nio.tcp.DefaultSocketChannelWrapper.read(DefaultSocketChannelWrapper.java:59)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.initReadHandler(NonBlockingSocketReader.java:173)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:141)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:345)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:330)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:248)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:201)

java.io.IOException: Broken pipe  - repeated exception!
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at com.hazelcast.nio.tcp.DefaultSocketChannelWrapper.write(DefaultSocketChannelWrapper.java:64)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter.writeOutputBufferToSocket(NonBlockingSocketWriter.java:353)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter.handle(NonBlockingSocketWriter.java:322)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter.run(NonBlockingSocketWriter.java:403)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.executeTask(NonBlockingIOThread.java:309)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.processTaskQueue(NonBlockingIOThread.java:300)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:244)
        at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:201)

com.hazelcast.core.HazelcastException: java.net.SocketException: Connection reset
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:73)
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
        at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:83)
        at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:57)
        at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:404)
        at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:507)
        at com.hazelcast.internal.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75)
        at com.hazelcast.internal.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42)
        at com.hazelcast.spi.impl.executionservice.impl.SkipOnConcurrentExecutionDecorator.run(SkipOnConcurrentExecutionDecorator.java:40)
        at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
        at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:158)
        at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:144)
        at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:53)
        at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:42)
        ... 11 common frames omitted

I’ll appreciate your help.

**Comment by emrahkocaman** [comment] 2017-02-22 08:00
Hi @osnatn , thanks for reporting.
Is there a specific need for below config?
```
networkConfig.setPort(5701);
networkConfig.setPortCount(4);
networkConfig.setPortAutoIncrement(true);
```

I'd recommend disabling port auto increment, this should prevent the closed connection exceptions.
You see the logs periodically because discovery split brain check is done every 120 secs. This period is configurable via system property `hazelcast.max.join.merge.target.seconds`. Please check details [here](http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#network-partitioning-split-brain-syndrome).

 About the last exception; again this happens when we query AWS for possible members during the split brain handler's periodic run. It's basically a failing http request to the related EC2 service. Could you please share your hazelcast-aws version?

**Comment by osnatn** [comment] 2017-02-26 14:02
Hi,
I'm using version 3.7.
Disabling port auto increment means also setting PortCount(1) instead of PortCount(4) so only port 5701 is used? Not sure if I understand when I should use enabled auto-increment?
Thanks, Osnat

**Comment by osnatn** [comment] 2017-02-27 15:01
No repeated connection close in logs and no exceptions anymore, after changing the configuration to:
networkConfig.setPort(5701);
networkConfig.setPortCount(1);
networkConfig.setPortAutoIncrement(false);

Thanks for your help although I can't say that I understand the auto increment issue and will appreciate if you can elaborate.
Thanks, Osnat

**Comment by emrahkocaman** [comment] 2017-03-02 07:48
Nice to hear that the problem is solved. 
Port auto-increment is useful when you're starting multiple Hazelcast instances in the same VM. So if 5701 is already occupied it'll try to bind it self to the next available one but beyond that this config is also used in discovery. Hazelcast will try to connect to a number of ports (defined by `portCount`) to all IPs returned from discovery service.

Closing this issue then, thanks for the update.

**Closed by emrahkocaman** 2017-03-02 07:48 UTC
